name: My Starter workflow 2
on: 
  workflow_dispatch:
jobs:
  call-workflow-using-branch:
    uses: ashrafalih/demo_called/.github/workflows/reusable-2.yml@testb1
#example:1: reusable workflow in same repo###########################################
# name: My Starter Workflow
# on:
#   workflow_dispatch:
# jobs:

#   call-workflow-in-local-repo:
#     uses: ./.github/workflows/reusable-workflow-1.yml
